---
title: "Tidytuesday Museum"
output: html_document
author: Ng Simin
date: "2022-11-22"
---

### Set up
``` {r setup, results = FALSE, message = FALSE, warning = FALSE}
library(ggplot2)
library(tidyverse)
library(Hmisc)
library(GGally)
library(ggmosaic)
library(maps)
library(gganimate)
library(gifski)

m <- read.csv("./museums.csv") 
# Hmisc::describe(m) 
# ggpairs(m, names(m)[22:28])
```

### Graph 1.1
Variables: Accreditation, Size
``` {r, warning = FALSE}
m %>% summarise(Accreditation, Size) %>% ggplot() +
  geom_mosaic(aes(product(Size), fill = Accreditation), show.legend = FALSE) +
  labs(title = "Relationship between Accreditation Status and Size of Museums") 
```

### Graph 1.2
Variables: Accreditation, Governance
```{r, warning = FALSE}
m %>% summarise(Accreditation, Governance) %>% 
  mutate(Governance = str_extract(Governance, "^[:alpha:]+(?=_|-)")) %>%
  ggplot() + geom_mosaic(aes(product(Governance), 
                           fill = Accreditation), show.legend = FALSE) + 
  labs(title = "Relationship between Governance and Size of Museums")
```

### Graph 2
Variables: Latitude, Longitude
``` {r}
m %>% mutate(lat = round(Latitude, 1), long = round(Longitude, 1)) %>%
  group_by(lat, long) %>% summarise(n = n(), .groups = "drop") -> mm

ggplot() + 
  geom_polygon(data = map_data("world", region = "UK"),
               aes(long, lat, group = group), 
               fill = "gray90", color = "black") + 
  coord_fixed(ratio = 1.3, xlim = c(-10,3), ylim = c(50.3, 59)) +
  geom_point(data = mm, aes(long, lat, size = n), alpha = .5) + 
  scale_size_area(max_size = 8) + theme_void() + 
  theme(legend.position = "none", plot.title = element_text(hjust = 0.5)) +
  labs(size = "Count", title = "Distribution of museums across UK")
```

### Improved Graph 2
Variables: Latitude, Longitude, Year_opened, Year_closed
``` {r}
m %>% summarise(open = Year_opened, close = Year_closed, 
                lat = round(Latitude, 1), long = round(Longitude, 1)) %>% 
  mutate(open = as.numeric(str_extract(open, "^[0-9]{4}")), 
         close = as.numeric(str_extract(close, "[0-9]{4}$")), 
         close = ifelse(close == 9999, 2021, close)) %>% 
  rowwise() %>% mutate(year = list(open:close)) %>% 
  ungroup() %>% mutate(open = NULL, close = NULL) %>% 
  unnest(year) %>% group_by(year, lat, long) %>% 
  summarise(count = n(), .groups = "drop") %>% unique() -> mm

ggplot() + 
  geom_polygon(data = map_data("world", region = "UK"),
               aes(long, lat, group = group), 
               fill = "gray90", color = "black") + 
  coord_fixed(ratio = 1.3, xlim = c(-10,3), ylim = c(50.3, 59)) +
  geom_point(data = mm, aes(long, lat, size = count), alpha = .5) + 
  scale_size_area(max_size = 8) + theme_void() + 
  theme(legend.position = "none", plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5)) +
  labs(size = "Count", subtitle = "Year: {frame_time}", 
       title = "Distribution of museums across UK") + 
  transition_time(year) + ease_aes('linear') -> p

animate(p, renderer = gifski_renderer())
anim_save("./Graph2.gif")
```
